# Generated by Django 4.1.7 on 2023-03-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('EmailID', models.EmailField(max_length=254, unique=True)),
                ('Role', models.CharField(blank=True, max_length=15)),
                ('UserStatus', models.BooleanField(default=True)),
            ],
        ),
    ]
