# Generated by Django 4.1.7 on 2023-03-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Password',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
