# Generated by Django 4.1.2 on 2023-04-05 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0003_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('MaterialID', models.AutoField(primary_key=True, serialize=False)),
                ('MaterialCode', models.CharField(max_length=255, unique=True)),
                ('MaterialName', models.CharField(max_length=25)),
                ('TotalQuantity', models.CharField(max_length=25)),
                ('ConsumedQuantity', models.CharField(max_length=25)),
                ('AddedTimestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedTimestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('VendorID', models.AutoField(primary_key=True, serialize=False)),
                ('VendorName', models.CharField(max_length=100)),
                ('VendorShopName', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=10)),
                ('EmailID', models.EmailField(max_length=254, unique=True)),
                ('Address', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=25)),
                ('State', models.CharField(max_length=25)),
                ('AddedTimestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedTimestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
