# Generated by Django 4.1.2 on 2023-04-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0004_rawmaterial_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='QtyType',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='ConsumedQuantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='TotalQuantity',
            field=models.IntegerField(default=0),
        ),
    ]
