# Generated by Django 4.1.2 on 2023-04-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0005_rawmaterial_qtytype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='QtyType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
