# Generated by Django 4.1.2 on 2023-04-07 17:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0008_alter_vendor_vendorcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addrawmaterial',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('TransactionDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('BatchNo', models.CharField(max_length=100)),
                ('OrderedQuantity', models.IntegerField()),
                ('ReceivedQuantity', models.IntegerField()),
                ('AmountPaid', models.IntegerField()),
                ('DamagedQty', models.IntegerField(null=True)),
                ('DamagedResion', models.CharField(max_length=100, null=True)),
                ('LossofAmount', models.IntegerField(null=True)),
                ('AddedTimestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedTimestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('MaterialID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krysta_app.rawmaterial')),
                ('VendorCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krysta_app.vendor')),
            ],
        ),
    ]
