# Generated by Django 4.1.2 on 2023-04-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0009_addrawmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrawmaterial',
            name='DamagedQty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addrawmaterial',
            name='DamagedResion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addrawmaterial',
            name='LossofAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
