# Generated by Django 4.1.2 on 2023-04-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0010_alter_addrawmaterial_damagedqty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrawmaterial',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
