# Generated by Django 4.1.2 on 2023-04-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0011_alter_addrawmaterial_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addrawmaterial',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
