# Generated by Django 4.1.2 on 2023-04-11 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0012_delete_addrawmaterial_delete_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('VendorID', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('VendorCode', models.CharField(max_length=100)),
                ('VendorName', models.CharField(max_length=100)),
                ('RegisteredName', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=25)),
                ('EmailID', models.EmailField(max_length=254, unique=True)),
                ('Address', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=25)),
                ('State', models.CharField(max_length=25)),
                ('Zip', models.CharField(default=0, max_length=10)),
                ('AddedTimestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedTimestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
