# Generated by Django 4.1.2 on 2023-04-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0015_rename_id_vendor_vendorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='VendorID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
