# Generated by Django 4.1.2 on 2023-04-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0016_alter_vendor_vendorid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Damaged',
            fields=[
                ('DamgeID', models.AutoField(primary_key=True, serialize=False)),
                ('DamagedQty', models.IntegerField(blank=True, null=True)),
                ('DamagedResion', models.CharField(blank=True, max_length=100, null=True)),
                ('LossofAmount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
