# Generated by Django 4.1.2 on 2023-04-11 09:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0017_damaged'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addrawmaterial',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('TransactionDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('BatchNo', models.CharField(max_length=25)),
                ('OrderedQuantity', models.IntegerField()),
                ('ReceivedQuantity', models.IntegerField()),
                ('AmountPaid', models.IntegerField()),
                ('AddedTimestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedTimestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('DamgeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krysta_app.damaged')),
                ('MaterialID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krysta_app.rawmaterial')),
                ('VendorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krysta_app.vendor')),
            ],
        ),
    ]
