# Generated by Django 4.1.2 on 2023-04-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0018_addrawmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='MaterialCode',
            field=models.CharField(max_length=255),
        ),
    ]
