# Generated by Django 4.1.2 on 2023-04-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0019_alter_rawmaterial_materialcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damaged',
            name='DamgeID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
