# Generated by Django 4.1.2 on 2023-04-14 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0022_packingmaterial_product_productdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('TotalLabours', models.IntegerField()),
                ('MorningShiftCount', models.IntegerField()),
                ('NightShiftCount', models.IntegerField()),
                ('MorningShiftAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('NightShiftAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AddedTimeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedTimeStamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
