# Generated by Django 4.1.2 on 2023-04-17 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0023_labour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('InvoiceNumber', models.CharField(max_length=10)),
                ('InwardNumber', models.CharField(max_length=20)),
                ('InvoiceDate', models.DateField()),
                ('RecievedDate', models.DateField()),
                ('VendorID', models.IntegerField()),
                ('AddedTimeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedTimeStamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
