# Generated by Django 4.1.2 on 2023-04-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0025_alter_addrawmaterial_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrawmaterial',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
