# Generated by Django 4.1.2 on 2023-04-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0028_formula_formulamaterials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
