# Generated by Django 4.1.2 on 2023-04-29 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0030_rename_id_invoice_invoiceid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulamaterials',
            old_name='RawMaterialID',
            new_name='MaterialID',
        ),
    ]
