# Generated by Django 4.1.2 on 2023-05-02 04:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0032_rename_id_formula_formulaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('ProductionID', models.AutoField(primary_key=True, serialize=False)),
                ('TransactionDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('FormulaId', models.IntegerField()),
                ('ProductionQuantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AddedTimeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedTimeStamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
