# Generated by Django 4.1.2 on 2023-05-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0033_production'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='FormulaId',
            new_name='FormulaID',
        ),
    ]
