# Generated by Django 4.1.2 on 2023-05-03 10:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0034_rename_formulaid_production_formulaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPacking',
            fields=[
                ('production_packing_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AddedTimeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedTimeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('PackingMaterialID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='krysta_app.packingmaterial')),
                ('ProductionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krysta_app.production')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionDetails',
            fields=[
                ('Pro_detailsID', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AddedTimeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedTimeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('MaterialID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='krysta_app.rawmaterial')),
                ('ProductionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krysta_app.production')),
            ],
        ),
    ]
