# Generated by Django 4.1.2 on 2023-05-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0035_productionpacking_productiondetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='ProductionID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
