# Generated by Django 4.1.2 on 2023-05-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0037_alter_invoice_recieveddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='LossofAmount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='damaged',
            name='LossofAmount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RecievedDate',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
