# Generated by Django 4.1.2 on 2023-05-15 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0039_labour_enterydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='FormulaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krysta_app.formula'),
        ),
    ]
