# Generated by Django 4.1.2 on 2023-05-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0041_sales_salesinvoice_salesdetails_sales_invoiceid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='InvoiceID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
