# Generated by Django 4.1.2 on 2023-05-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0042_alter_salesinvoice_invoiceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='TotalProductionQty',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='formula',
            name='TotalSaledQty',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True),
        ),
    ]
