# Generated by Django 4.1.2 on 2023-05-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0043_formula_totalproductionqty_formula_totalsaledqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='InvoiceID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
