# Generated by Django 4.1.2 on 2023-05-25 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0046_salesdamage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdamage',
            name='ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_damage', to='krysta_app.salesdetails'),
        ),
    ]
