# Generated by Django 4.1.2 on 2023-05-26 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0047_alter_salesdamage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='production',
            name='FormulaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_details', to='krysta_app.formula'),
        ),
        migrations.AlterField(
            model_name='productiondetails',
            name='ProductionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_material', to='krysta_app.production'),
        ),
        migrations.AlterField(
            model_name='productionpacking',
            name='ProductionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_material', to='krysta_app.production'),
        ),
    ]
