# Generated by Django 4.1.2 on 2023-05-26 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0048_category_alter_production_formulaid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='Category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='krysta_app.category'),
        ),
    ]
