# Generated by Django 4.1.2 on 2023-05-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0049_formula_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='BatchNo',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='BatchNo',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
    ]
