# Generated by Django 4.1.2 on 2023-05-30 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0051_salesdetails_productid_salesdetails_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdetails',
            name='FormulaID',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='krysta_app.formula'),
        ),
    ]
