# Generated by Django 4.1.2 on 2023-05-30 10:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0052_alter_salesdetails_formulaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionDamage',
            fields=[
                ('ProductionDamageID', models.AutoField(primary_key=True, serialize=False)),
                ('DamagedQuantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DamageReason', models.CharField(max_length=500)),
                ('LossPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AddedTimeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedTimeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_damage', to='krysta_app.productiondetails')),
            ],
        ),
    ]
