# Generated by Django 4.1.2 on 2023-05-30 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0053_productiondamage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiondamage',
            name='ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_damage', to='krysta_app.production'),
        ),
    ]
