# Generated by Django 4.1.2 on 2023-06-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0055_alter_productiondamage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='ConsumedQuantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='TotalQuantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
