# Generated by Django 4.1.2 on 2023-07-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0056_alter_rawmaterial_consumedquantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='Formulas',
            field=models.CharField(default='', max_length=100),
        ),
    ]
