# Generated by Django 4.1.2 on 2023-07-14 05:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0057_labour_formulas'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSale',
            fields=[
                ('BatchID', models.AutoField(primary_key=True, serialize=False)),
                ('BatchNo', models.CharField(blank=True, max_length=25, null=True)),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AddedTimeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedTimeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_batch', to='krysta_app.salesdetails')),
            ],
        ),
    ]
