# Generated by Django 4.1.2 on 2023-07-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0058_batchsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdetails',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
