# Generated by Django 4.1.2 on 2023-07-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0059_alter_salesdetails_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='BatchQty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
