# Generated by Django 4.1.2 on 2023-07-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0060_production_batchqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='BatchQty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
