# Generated by Django 4.1.2 on 2023-07-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0061_alter_production_batchqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damaged',
            name='DamgeID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='formula',
            name='FormulaID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='InvoiceID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='production',
            name='ProductionID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sales',
            name='SalesID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salesdetails',
            name='ID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='InvoiceID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
