# Generated by Django 4.1.2 on 2023-07-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0062_alter_damaged_damgeid_alter_formula_formulaid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='EmailID',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='Phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='VendorName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
