# Generated by Django 4.1.2 on 2023-09-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0063_alter_vendor_emailid_alter_vendor_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='InwardNumber',
            field=models.CharField(max_length=35),
        ),
    ]
