# Generated by Django 4.1.2 on 2023-10-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krysta_app', '0064_alter_invoice_inwardnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='InvoiceNumber',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='InwardNumber',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='InvoiceNumber',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='InwardNumber',
            field=models.CharField(max_length=50),
        ),
    ]
